site_name: GIG Cymru NHS Wales - Architecture Decision Records
site_url: https://gig-cymru-nhs-wales.github.io/
repo_url: https://github.com/GIG-Cymru-NHS-Wales/Architecture-Decision-Records/
docs_dir: doc
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: custom

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences