append_unmatched: true
flatten_single_child_sections: true
nav:
  - Home: index.md
  - Principles:
    - DHCW Design Authority:
      - design-authority/principles/index.md
      - Principles: design-authority/principles/
  - Decisions:
    - DHCW Design Authority:
      - design-authority/dhcw/index.md
      - Decisions: design-authority/dhcw/
<<<<<<< HEAD
    - Decision Template: design-authority/dhcw/architecture-decision-record-template.md
=======
    - Enterprise Architecture Metamodel:
      - design-authority/ea-metamodel/index.md
      - Metamodel Decisions: design-authority/ea-metamodel/ 
    - Template: design-authority/dhcw/architecture-decision-record-template.md
>>>>>>> e3d9f93 (Start capturing EA Metamodel decisions)
    - Meta Decisions:
      - meta-decisions/*
    - Development:
      - "*"